### ISSUE TITLE
Password reset emails not functioning

### ISSUE THREAD

**Issue by bradleyboy** [koken/docker-koken-lemp#7]
PHP's mail() function is not working inside the container, probably because sendmail is not installed. I tried installing sendmail, but then sending mail just hangs. Will need some investigation on what the best course of action is here.

**Comment by bradleyboy** [comment]
Will soon be a non-issue in Koken 0.21. More info soon.

**Comment by truedat101** [comment]
Sorry, how was this fixed or resolved?

**Comment by nicokaiser** [comment]
> Sorry, how was this fixed or resolved?

Koken seems not to be developed anymore, so either this issue has been resolved (current version is 0.22.24) or it will never be. NetObjects (who aquired Koken in 2015) seems to be completely dead.

**Comment by truedat101** [comment]
@nicokaiser oh wow, so that explains why the docker hasn't been touched in four years.   The software is still useful.  This is too bad.
